### ISSUE TITLE
How to build in Windows?

### ISSUE THREAD

**Issue by PiskunovSS** [rgl/ubuntu-vagrant#3]
The instructions do not understand how to run the image creation in Windows

**Comment by rgl** [comment]
you need to install the dependencies mentioned in the [README](https://github.com/rgl/ubuntu-vagrant/blob/master/README.md), either manually, or with [chocolatey](https://chocolatey.org/), then you need to install `make` (with something like [rgl/visual-studio-community-vagrant/provision.ps1](https://github.com/rgl/visual-studio-community-vagrant/blob/d38a538646c0df734a6be304c174a1cbe58f0b76/provision.ps1#L165-L206)) or by directly executing `packer build` (like its done inside the [Makefile](https://github.com/rgl/ubuntu-vagrant/blob/master/Makefile)).
