### ISSUE TITLE
Plans to support Virtualbox 6.x?

### ISSUE THREAD

**Issue by nimaim** [rgl/ubuntu-vagrant#4]
I tried building this recently on the latest Virtualbox (6.0.4 at the time of this posting) and it failed (I don't have the exact error in front of me as I promptly downgraded and rebuilt it just fine with 5.2.26). It seems their VboxManage CLI has changed. Just wondering if you plan to support the newer Virtualbox.

If you need the exact error, I can try building it with 6.0 again later.

**Comment by rgl** [comment]
are you using the latest vagrant 2.2.3?

**Comment by nimaim** [comment]
Yes, latest Vagrant (2.2.3) on a Linux Mint 19.1 x64 host. I can get you the exact error once I set up a VM, I don't want to mess up my original set up with vbox 5.2.x, which works. It's probably a very simple change to some vbox commands in the json file, but I am not too familiar with those.

**Comment by rgl** [comment]
that's really odd, it works fine on a ubuntu 18.04 host and virtualbox 6.0.4.

**Comment by nimaim** [comment]
Thanks for verifying it works @rgl, let me do some more testing and get back to you. I am positive this did not work but downgrading to latest 5.2.x had me building this successfully again. I just was not 100% sure whether it was this base box or your jenkins build (+ ubuntu slave).

**Comment by rgl** [comment]
I hope this is now working, if its not please reopen this issue.
