### ISSUE TITLE
make throws No rule to make a target

### ISSUE THREAD

**Issue by ghost** [rgl/ubuntu-vagrant#5]
Hi.

I get this error message when executing the make build-virtualbox command

AzureAD+SensitiveValue@LAPTOP-SensitiveValue MINGW64 ~
$ make build-virtualbox
**make: *** No rule to make target 'build-virtualbox'.  Stop.**

AzureAD+SensitiveValue@LAPTOP-SensitiveValue MINGW64 ~

I have started C:\tools\msys64\mingw64 from an adminstrator and  a non administrator powershell prompt and run the make build-virtualbox command and I get the same error message:

I can't find the makefile anywhere in Mingw64 bash shell

In the powershell prompt I can find the make file but I get this error message instead:

make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ make build-virtualbox
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I have a Windows host and followed these steps:

1. I have downloaded the files from github.
2. I have executed following commands in an administrator powershell window:

choco install -y virtualbox --params "/NoDesktopShortcut /ExtensionPack"
choco install -y packer vagrant jq msys2

3. I have opened the mingw64 bash shell by executing C:\tools\msys64\mingw64.exe
4. I have executed these commands in the mingw64 bash shell:

pacman --noconfirm -Sy make zip unzip tar dos2unix netcat procps xorriso mingw-w64-x86_64-libcdio
for n in /*.ini; do
    sed -i -E 's,^#?(MSYS2_PATH_TYPE)=.+,\1=inherit,g' $n
done
exit

5. I have restarted the mingw64 bash by executing C:\tools\msys64\mingw64.exe
6. make build-virtualbox gives this error:

AzureAD+MichaelDoganbas@LAPTOP-4O0UBBTT MINGW64 ~
$ make build-virtualbox
make: *** No rule to make target 'build-virtualbox'.  Stop.

AzureAD+MichaelDoganbas@LAPTOP-4O0UBBTT MINGW64 ~

Windows Host
System Type: 64-bit operating system, x64-based processor
Operating System: Windows 10 Pro
Version: 20H2
OS Build: 19042.685

Provider/Hypervisor
Software: Oracle VirtualBox
Version: 6.1.16 r140961 (Qt 5.6.2)

I think I should be able to locate the makefile in the mingw64 bash shell but I am just a beginner in this field and I am a beginner in "linux". Is this a bug? Or is it just me that needs to do a additional step? But I feel I have read your instructions very carefully:-)

I would really appreciate if you help me to troubleshoot this issue.

Best regards

**Comment by rgl** [comment]
Are you in this repository checkout directory? Make sure of that by `cd ubuntu-vagrant` and `ls -laF`, you should see the `Makefile` file, `Vagrantfile`, etc.

**Comment by ghost** [comment]
I solved it.

1. `C:\tools\msys64\mingw64.exe` (opened elevated Mingw64 Bash Shell)
2. `pacman --noconfirm -Sy git` (installed git command - I didn't see this in the readme)
3. `cd /home/githu` (changed directory)
3. `git clone https://github.com/rgl/ubuntu-vagrant.git` (cloned repository)
4. `cd ubuntu-vagrant/` (changed directory)
5. `ls -af` (listed all content and now I can see `Makefile`, etc
6. `make build-virtualbox`
7. After almost 16 minutes I have new shiny ubuntu 20.04 box:-)

Thank you for taking the time to lead me in the right direction.

**Comment by rgl** [comment]
Nice!
