### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by ghost** [rgl/ubuntu-vagrant#6]
Hi.

I get an error message when I have executed the command:

`~/ubuntu-vagrant/example/vagrant up --provider=virtualbox --no-destroy-on-error --no-tty`

The error message is:

_Error message start_

==> vagrant: You have requested to enabled the experimental flag with the following features:
==> vagrant:
==> vagrant: Features:  typed_triggers
==> vagrant:
==> vagrant: Please use with caution, as some of the features may not be fully
==> vagrant: functional yet.
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Running action triggers before up ...
==> default: Running trigger...
==> default: Box 'ubuntu-20.04-amd64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'ubuntu-20.04-amd64' (v0) for provider: virtualbox
    default: Downloading: ubuntu-20.04-amd64

    default: An error occurred while downloading the remote file. The error message, if any, is reproduced below. Please fix this error and try again.

Couldn't open file C:/tools/msys64/home/<Username>/ubuntu-vagrant/example/ubuntu-20.04-amd64

_Error message end_

Host: Windows 10 Pro 20H2 build 19042.685
Vagrant version: 2.2.14
Provider model/version: Virtualbox   6.1.16 r140961 (Qt 5.6.2)

I have given Users and Authenticated Users Full Control to example directory and subfolders and files in Windows 10 File Explorer. The example directory is not encrypted. I have restarted the mingw64 bash shell. Issue still exists.

Do you know how I can troubleshoot this further?

Here are some screenshots too:

![ErrorMessage](https://user-images.githubusercontent.com/18162950/103892319-b0485880-50eb-11eb-8840-703479585ec5.png)
![ExampleDirectoryContentAndPermissions](https://user-images.githubusercontent.com/18162950/103892322-b0e0ef00-50eb-11eb-8e77-038be760add3.png)
![Ubuntu-vagrantDirectoryContentAndPermissions](https://user-images.githubusercontent.com/18162950/103892323-b0e0ef00-50eb-11eb-9e69-ce8ab1ec9d77.png)

**Comment by rgl** [comment]
It seems you didn't did add the box to your local vagrant instance with the vagrant box add command. 

What is the output of the command vagrant box list command?

**Comment by ghost** [comment]
PS C:\tools\msys64> vagrant box list
windows-2019-amd64 (virtualbox, 0)
PS C:\tools\msys64>

You seem to be correct:-) I will add the ubuntu box after I have started the domain controller. I will get back to you as soon as possible...

**Comment by ghost** [comment]
I added the box with this command:

PS C:\tools\msys64\home\username\ubuntu-vagrant> `vagrant box add --name ubuntu-20.04-amd64-virtualbox .\ubuntu-20.04-amd64-virtualbox.box`
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'ubuntu-20.04-amd64-virtualbox' (v0) for provider:
    box: Unpacking necessary files from: file://C:/tools/msys64/home/<username>/ubuntu-vagrant/ubuntu-20.04-amd64-virtualbox.box
    box:
==> box: Successfully added box 'ubuntu-20.04-amd64-virtualbox' (v0) for 'virtualbox'!

And then I list the boxes:

PS C:\tools\msys64\home\username\ubuntu-vagrant> `vagrant box list`
ubuntu-20.04-amd64-virtualbox (virtualbox, 0)
windows-2019-amd64                 (virtualbox, 0)
PS C:\tools\msys64\home\username\ubuntu-vagrant>

And I still get the same error message

_Couldn't open file C:/tools/msys64/home/username/ubuntu-vagrant/example/ubuntu-20.04-amd64_

![image](https://user-images.githubusercontent.com/18162950/104004658-48a21400-51a4-11eb-8588-f94856225092.png)

**Comment by rgl** [comment]
Vagrant is not finding a box named `ubuntu-20.04-amd64`.

If you look at the box names returned by `vagrant box list` you'll see one named `ubuntu-20.04-amd64-virtualbox` instead of the expected `ubuntu-20.04-amd64`.

Try to have a look at the `Makefile` and infer how its showing the entire `vagrant box add` command at https://github.com/rgl/ubuntu-vagrant/blob/master/Makefile#L35-L37

**Comment by ghost** [comment]
In mingw64 bash shell I remove box with:

AzureAD+username@LAPTOP-?? MINGW64 ~/ubuntu-vagrant
`vagrant box remove ubuntu-20.04-amd64-virtualbox`

And then added the box with this command:

AzureAD+username@LAPTOP-?? MINGW64 ~/ubuntu-vagrant
`vagrant box add ubuntu-20.04-amd64 ubuntu-20.04-amd64-virtualbox.box`

And it seems to be working now! Thank you for your help:-)

**Comment by rgl** [comment]
no problem!
